name: article_screen
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Abril Fatface
      fonts:
        - asset: fonts/AbrilFatface-Regular.ttf
    - family: Arbutus Slab
      fonts:
        - asset: fonts/ArbutusSlab-Regular.ttf
    - family: Work Sans
      fonts:
        - asset: fonts/WorkSans-Regular.ttf
        - asset: fonts/WorkSans-Italic.ttf
          style: italic
        - asset: fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: fonts/WorkSans-Bold.ttf
          weight: 700
